version: "2"

volumes:
  data-volume:

services:
  app:
    container_name: kb-search
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
