version: "2"

volumes:
  data-volume:

services:
  app:
    container_name: kb-search
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: microdocker/mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  gateway:
    container_name: dimi
    image: kamerbaas/api-gateway
    ports:
      - "8081:8080"

